/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.davidrotabor.introduccionPoo;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);

        int indiceProductos = 0;

        String[] nombresPersonas = new String[100];
        int[][] compras = new int[100][100];

        String[] categoriasProductos = new String[10000];
        String[] nombresProductos = new String[10000];
        double[] preciosProductos = new double[10000];

        System.out.println("Cuántas personas van a comprar?");
        int cantidadPersonas = scan.nextInt();

        for (int i = 0; i < cantidadPersonas; i++) {
            System.out.println("Cuál es tu nombre?");
            scan.nextLine();
            nombresPersonas[i] = scan.nextLine();

            System.out.println("Cuántas productos va a comprar?");
            int cantidadProductos = scan.nextInt();

            for (int j = 0; j < cantidadProductos; j++) {
                System.out.println("Cuál es la categoria del producto");
                scan.nextLine();
                categoriasProductos[indiceProductos] = scan.nextLine();

                System.out.println("Cuál es el nombre del producto");
                nombresProductos[indiceProductos] = scan.nextLine();

                System.out.println("Cuál es el precio del producto");
                preciosProductos[indiceProductos] = scan.nextDouble();

                compras[i][j] = indiceProductos;
                indiceProductos++;
            }

        }

        for (int i = 0; i < 100; i++) {
            if (nombresPersonas[i] == null) {
                break;
            }

            System.out.println(nombresPersonas[i] + " tiene estas compras:");

            for (int j = 0; j < 100; j++) {
                if (compras[i][j] == 0 && j != 0) {
                    break;
                }

                System.out.println("Categoria: " + categoriasProductos[compras[i][j]]);
                System.out.println("Nombre: " + nombresProductos[compras[i][j]]);
                System.out.println("Precio: " + preciosProductos[compras[i][j]]);
            }
        }

    }
}
