/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.davidrotabor.introduccionPoo;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {

        Scanner scan = new Scanner(System.in);

        List<Persona> personas = new ArrayList<Persona>();

        System.out.println("Cuántas personas van a comprar?");
        int cantidadPersonas = scan.nextInt();

        for (int i = 0; i < cantidadPersonas; i++) {
            System.out.println("Cuál es tu nombre?");
            scan.nextLine();

            Persona persona = new Persona(scan.nextLine());

            System.out.println("Cuántas productos va a comprar?");
            int cantidadProductos = scan.nextInt();

            for (int j = 0; j < cantidadProductos; j++) {
                System.out.println("Cuál es la categoria del producto");
                scan.nextLine();
                String categoria = scan.nextLine();

                System.out.println("Cuál es el nombre del producto");
                String nombreProducto = scan.nextLine();

                System.out.println("Cuál es el precio del producto");
                double precioProducto = scan.nextDouble();

                persona.agregarProducto(categoria, nombreProducto, precioProducto);
            }
            
            personas.add(persona);
        }

        for (Persona persona : personas) {
            
            System.out.println(persona.nombre + " compró:");

            for (int i = 0; i < persona.categoriasProductos.size(); i++) {
                System.out.println("Categoria: " + persona.categoriasProductos.get(i));
                System.out.println("Nombre: " + persona.nombresProductos.get(i));
                System.out.println("Precio: " + persona.preciosProductos.get(i));
            }
        }

    }
}
